### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by DavidHooper** [jrochkind/attr_json#1]
I like this implementation.

What's next for this gem and what are you going to call it?

I'd be interested in implementing this into my existing code for IncoDocs to make prototyping new documents easier.

I also had my own implementation for how to nest attributes. You can check it out [here](https://github.com/DavidHooper/jsonb_store).

**Comment by jrochkind** [comment]
Thanks for feedback!

I am not sure what to call it -- any suggestions?

I am not sure at this point what's next -- ideally I would like to get some more feedback before a release.  If you wanted to try it out (bundle from github) and see if it behaves as you expect and if you run into any problems, it would be quite helpful. 

Do you have any ideas, are you interested in collaboration?

**Comment by buren** [comment]
I agree! This project looks very interesting! I've been meaning to use `jsonb` more in a Rails project and this really looks like something I'd love to use :) Great work!

I'm not good at naming things (damn thats hard..), but my first thought was maybe `attr_json`? There aren't any existing gems with that name: 
https://rubygems.org/search?utf8=%E2%9C%93&query=attr_json

**Comment by onomated** [comment]
Really interested in getting this gem to work.  Discovered this after trying out `jsonb_accessor` and struggling to get embedded types to work.  
Name suggestion: `pg_jsonator` if you intend to support Postgres only, or `jsonator` for possible json support for other platforms.

**Comment by jrochkind** [comment]
Hi, I to put another chunk of work into this in the next couple months, it fits into some day job work. 

I appreciate the feedback some have left so far in Issues, please keep it coming. 

What I plan to work on next:  

* dependable dirty tracking
* polymorphic attributes
* any open issues, one way or another

Not sure of schedule, but i'm still in it, and believe I will have some time in the next couple months. Please keep the suggestions and questions coming!

**Comment by jrochkind** [comment]
I think i might just release as `json_attribute` after all, although it runs the risk of confusion with the existing little-used not-for-rails-5-yet `json_attributes`. Any thoughts welcome. 

I considered `rails_json_attribute`, which would be more accurate, but I don't want to type `RailsJsonAttribute::` every time I need to type a namespaced class or module! (which users of the gem have to do sometimes too).

**Comment by onomated** [comment]
👏Been using this in production with absolutely no issues.  Looking forward to an official release on rubygems.  Haven't needed any of the two new features listed above.  What do you mean by polymorphic attributes?  Polymorphic associations in jsonb fields?

**Comment by jrochkind** [comment]
polymorphic:  I mean declaring a json_attribute with at type that can hold more than one type of value. Different JsonAttribute::Model's, or "primitive" types, or a mixture.  With or without `array: true`. 

Thanks for testing it out, @onomated, I'm glad to hear it's been working fine. 

Backwards incompat changes are still possible before 1.0 (I'm not going to release as 1.0 yet), but I don't anticipate any at present.

**Comment by jrochkind** [comment]
Several additional features are things that _I_ need for the use I'm hoping to use this for, that I'm not at yet. :)

**Comment by jrochkind** [comment]
This is now tested in travis on Rails 5.2.0.rc -- no changes were needed to implementation for tests to pass, which is a good sign. 

Also, attribute-by-attribute dirty tracking support is now implemented. I'm awfully happy with how it turned out, I think it's pretty sweet.  See [doc](../blob/master/doc_src/dirty_tracking.md). 

All that typing of `json_attribute_changes` in testing that feature makes me want a shorter gem name. I'm leaning toward `json_attr`.  In code, all instances of `JsonAttribute` will change to `JsonAttr`, and the `json_attribute` class macro will change to `json_attr`.  So anyone using existing code will have to change those. Any thoughts?

**Comment by onomated** [comment]
Pluralize i.e. `json_attrs`?  Or how about `json_embed` (`JsonEmbed`)?

**Comment by jrochkind** [comment]
@onomated Are you not a fan of `json_attr`, then? :)

**Comment by onomated** [comment]
@jrochkind  The pluralized form sounds more natural to me.  Naming things is tough, so would be fine with either!  More looking forward to an official release

**Comment by jrochkind** [comment]
OK, i'll try to get on a name choice and release to rubygems.  Thanks @onomated !

It _will_, though, still be pre-1.0 for some time, meaning backwards compat changes, even significant ones _can_ happen.  For how long depends on how much time I can find to work on it, and how many other people can help find any problems or identify unmet use cases.

**Comment by jrochkind** [comment]
Okay, I just merged some pretty slick support for form builders, which I'm pretty excited about. This was a major feature area that was important to me, that I wasn't sure how easy it would be to pull off in a non-insane way -- but I think I have.  With travis integration test for working with both simple_form and cocoon. 

The implementation ended up being a bit more complex/long then I would have liked, it turns out Rails has all sorts of weird parts here. (I never even really paid attention to Rails multi-parameter assignment before). 

So any feedback is welcome, either code review or based on trying it out -- would be great. 

I gotta pick a name and actually deploy to rubygems. The name choice is still stressing me out, heh. The only ones I can think of that satisfy me are the current `json_attributes`, or `json_attr`. 

If I change to `json_attr` , the module namespace will change to `JsonAttr`, and all methods beginning `json_attribute_` will change to `json_attr_`, including the main method for creating an attribute -- will be eg `json_attr :attr_name, :string` instead of `json_attribute :attr_name, :string`. I _really_ like tagging _everything_ with the gem name, so when using in a more complex project it's obvious where the methods and modules are coming from. 

Advantage of `json_attr` is that it's a lot shorter to type when it's everywhere, disadvantage is that I have no idea how to pronounce it out loud, which hopefully people will do to tell others about the gem, heh. 

I'll flip a coin or something, but any last minute feedback on the name welcome. :)

**Comment by jrochkind** [comment]
Hah, so unhappy with my naming choices. How about json_access/JsonAccess?

**Comment by jrochkind** [comment]
Okay I think I'm going with @buren 's suggestion for `attr_json`. :)

**Comment by jrochkind** [comment]
With the release of attr_json 0.3.0, I consider this basically feature-complete for a 1.0 release. (Most interesting major new thing in 0.3.0 is [some support for 'polymorphic' attributes](https://github.com/jrochkind/attr_json/blob/master/lib/attr_json/type/polymorphic_model.rb)). 

It probably still has edge case bugs, and perhaps is lacking things I haven't thought of that are needed for some sensible use cases I haven't run into yet. I am still not using this in a real project yet myself.  So needs more use before 1.0. All feedback of any kind remains welcome. 

Do feel free to tell your friends and neighbors, and I will probably try advertising it somewhat.

**Comment by jrochkind** [comment]
Anybody been using 0.3.0?

**Comment by onomated** [comment]
Haven't updated yet, been swamped.  Been using the previous version in prod now for almost a year with no hiccups whatsoever.  I'll look into upgrading some time this month and let you know how it goes.

**Comment by jrochkind** [comment]
@DavidHooper curious if you've played with this as it's developed, or since?

**Comment by jrochkind** [comment]
Closing this old discussion issue with the imminent release of master as 1.0.0. But feel free to get in touch with any questions or concerns about anything.
