### ISSUE TITLE
[Question] How would I migrate from store_model?

### ISSUE THREAD

**Issue by drewbaumann** [jrochkind/attr_json#104]
Hello,

I have implemented a new feature on one of my companies apps using store_model, but realized that this gem has some nice features like dirty tracking. How would I go about migrating from the store_model gem? One of the things I like about store_model is the ability to write classes that encapsulate the behavior of the json fields. I assume that I can do the same using `AttrJson::Model`, but might be missing something as my records are showing up as empty.

Here is what I have so far:

```ruby
class Shop::Messaging
  include AttrJson::Model

  attr_json :reminder, :string, default: I18n.t("sms.reminder_notice")
  attr_json :replenish, :string, default: I18n.t("sms.replenish_notice")
  attr_json :welcome, :string, default: I18n.t("sms.welcome_no_name")
end
```

```ruby
class Shop < ApplicationRecord
  include AttrJson::Record
  include AttrJson::Record::QueryScopes

  attr_json :messaging, Shop::Messaging.to_type, default: Shop::Messaging.new
```

Do I need to drop the default? Specify that `messaging` is the column in the database?

Thank you!

**Comment by jrochkind** [comment]
Hi, I'm not familiar with store_model. It's this one? https://github.com/DmitryTsepelev/store_model

attr_json by default wants your attributes to be one key in a column that by default is called `json_attributes`. So:

    attr_json :messaging, Shop::Messating.to_type

Would mean you have a `json_attributes` column in your db, which contains a hash that's like `{ "messaging" => hash_for_model }`

Do you instead want a `messaging` column in your db, that directly contains the hash for a single model? 

Does this part of the README answer your question? https://github.com/jrochkind/attr_json#single-attrjsonmodel-serialized-to-an-entire-json-column

Doing that actually uses very little of attr_json -- you don't get this gem's dirty tracking for instance, but you should get Rails built-in dirty tracking working fine I think. I would consider it a bonus to be using very little of this gem though, you are depending on less, using more of Rails. While I am using this gem in production happily, lately I have become a little bit less happy with it's long-term sustainability, and looking more at https://github.com/madeintandem/jsonb_accessor

**Comment by drewbaumann** [comment]
@jrochkind Yes that is the gem I speak of. This was very helpful. 

>Do you instead want a messaging column in your db, that directly contains the hash for a single model?

Correct. Also your [suggested part of the README](https://github.com/jrochkind/attr_json#single-attrjsonmodel-serialized-to-an-entire-json-column) was exactly what I needed!

>While I am using this gem in production happily, lately I have become a little bit less happy with it's long-term sustainability, and looking more at https://github.com/madeintandem/jsonb_accessor

So basically this gem might lose support before long?

**Comment by jrochkind** [comment]
> So basically this gem might lose support before long?

I guess I don't have a for sure answer, but I guess probably not after all, I was just feeling insecure maybe. 

The good news is it already passes all tests in Rails 6.1.0.rc1 without any changes needed at all, it just worked -- and passed tests in Rails 6.0.0 after being written for 5.2 and earlier without any changes at all too. So honestly I think it will probably keep working with very little maintenance regardless. 

There are also a variety of users at this point, and I have merged pull requests from a few other devs. 

The main app I work on depends on this, so as long as I am working on it, I'll need to keep this working -- OR have a good migration path to another gem. 

I have just started realizing that jsonb_accessor does some things smoother than this gem, the main thing it's lacking is support for models that serialize to hashes as we're talking about here (instead of just primitives) -- but I'm considering looking into how hard it would be to add that functionality to jsonb_accessor as a PR or a third-party gem. But nothing's going to happen right away.
