### ISSUE TITLE
Nested Form attributes with array types

### ISSUE THREAD

**Issue by alliedarmour** [jrochkind/attr_json#110]
First off, I love your gem as it helps me building a project for my university - thanks!

My problem is the following: We're building a healthcare application where we need to construct FHIR datasets / json objects from Rails forms. The normal attributes are working fine, but some attributes are stored in an new array inside the hash and therefor need to have a name like `"resource[name][ ][prefix][ ]"` - notice the empty array sign to tell Rails to save this as an array.

The structure looks something like this:

```
{
  "id": "7632922c-8977-4126-91ec-4db42bbc95ed",
  "name": [
    {
      "text": "Dr Maximilian Rohleder-Kirsch",
      "given": [
        "Maximilian"
      ],
      "family": "Rohleder-Kirsch",
      "prefix": [
        "Dr"
      ]
    }
  ],
  "active": true,
  "gender": "male",
  "address": [
    {
      "use": "home",
      "line": [
        "Wilhelmstraße"
      ],
      "type": "physical",
      "postalCode": "35614"
    }
  ],
  "birthDate": "2020-12-14",
  "resourceType": "Patient",
  "deceasedBoolean": false,
  "deceasedDateTime": null
}
```
What I did then was reading your form guide and put this the accepted nested attributes into my patient model:
`attr_json_accepts_nested_attributes_for :name`

`attr_json :name, HumanName.to_type, array: true
`
The name itself is a class with the `AttrJson::Model` included and looks like this:
```
class HumanName
    include AttrJson::Model

    attr_json :family, :string
    attr_json :text, :string
    attr_json :given, :string, array: true
    attr_json :prefix, :string, array: true
    attr_json :suffix, :string, array: true
end
```

Now my form looks like this:

```
<%= form_with(model: @patient, class: "col s12", url: patients_path, local: true) do |f| %>
    <%= f.fields_for :resource do |ff| %>
        <%= ff.hidden_field :local_id, value: SecureRandom.uuid %>
        <%= ff.fields_for :name do |name_field| %>
            <div class="input-field col l6 m12 s12">
                <%= name_field.text_field :prefix %>
                <%= name_field.label :prefix, "Titel" %>
            </div>
        <% end %>
    <% end %>
    <%= button_tag "Patient anlegen", type: "submit", class: "btn waves-effect btn-block light-green" %>
<% end %>
```

It's working but the name should be passed as an array to the params (notice the `array: true` in my model) but it's passed as an regular hash and the name of the form field is:

`patient[resource][name][prefix]` but should be like this: `patient[resource][name][ ][prefix][ ]`. 

Do I have to manually specify the names on the form fields to get this to work?

Sorry for the long text and thanks for any help!

**Comment by jrochkind** [comment]
Hi, thanks for trying out the gem and getting in touch. 

i honestly really don't know. I have never seen this form before ever: `resouce[name]**[ ]**[prefix]` -- oh wait, you are just using `**` as an placeholder. What you really need is eg: `patient[resource][name][][prefix][]`. 

Note, you put a space between the empty brackets to make it `[ ]`, but I'm pretty sure it should really be `[]`, no space between the brackets, yes? 

I haven't looked at this in a while, so I'm looking at my own consuming code as well as attr_json to remind myself what the options are. 

I don't think I have ever tried a nested structure quite this complex. I have done things where...  aha, looking at my examples, instead of using empty brackets, I use brackets with number indexes, which Rails also supports, so one of my example input names looks like: `work[external_id_attributes][0][value]`

How have I done that?

Looking at my code, it looks like the way I do this is... using a `repeatable_attr_input`, but where does that come from, it's not in attr_json. 

https://github.com/sciencehistory/scihist_digicoll/blob/master/app/views/admin/works/_work_fields.html.erb#L9-L11`

oh right, I wrote my own wrapper for use with `cocoon`. You don't mention cocoon, but you need some way of adding/removing elements from that array, yes? Unless you don't?  Here is some discussion of cocoon in attr_json docs: https://github.com/jrochkind/attr_json/blob/master/doc_src/forms.md#cocoon

Here is the extra helper method I wrote, not included in attr_json, for dealing with forms with repeated models and cocoon:

https://github.com/sciencehistory/kithe/blob/18146f4ada58cd12033867859e238f4b4cfe06ce/app/simple_form_enhancements/kithe/form_builder.rb#L10-L45

https://github.com/sciencehistory/kithe/blob/18146f4ada58cd12033867859e238f4b4cfe06ce/app/simple_form_enhancements/kithe/repeatable_input_generator.rb

Although I think you should be able to use cocoon directly too. 

I guess I think hypothetically it should be possible without cocoon. But you might need to just construct the input names you need, there might not be anything in Rails to do it for you -- I'm honestly not sure.  You just have to write the code on the form-generation end to make sure it's generating the input names that I think you already know you want. 

Rails "magic form handling" gets really complicated with these complex nested structures. It really gets confusing. I had some second thoughts about even trying to support it. I see you are trying to use "id" values in your nested models with UUIDs -- I'm not sure I ever worked out how to get that to work as you would want with Rails "automatic" form handling, when editing existing objects, where you want to make sure the same existing object gets edited. 

The other option is handling the model creating/setting yourself on the back-end. Instead of just being able to do the rails "magic" of `model.assign_attributes(params)`, you have to write your own code to take what's in `params[:whatever]`, and turn it into the model objects you want. If I were to do it over again, I might encourage that way and try to provide some examples for that, instead of encouraging using rails "automatic" `assign_attributes`. But that way should still be possible with `attr_json` if you want to explore it. 

I hope some of this information helps. I think you might have a couple options. Sorry, I don't think I have time debug or figure out a solution for you myself right now. Please let me know if you figure anything out!

**Comment by alliedarmour** [comment]
Thanks for your detailes answer @jrochkind! 
As I don't need any jQuery dynamic form fields (I do it myself with StimulusJS - I hate jQuery :laughing:) I finally managed to do it with the standard Rails forms and your gem!

I will try to explain what I did in case somebody else might want to build more complex JSON structures.

The complete form looks like this now:

```
<%= form_with(model: @patient, class: "col s12", url: patients_path, local: true) do |f| %>
    <%= f.fields_for :resource do |ff| %>
        <%= ff.hidden_field :local_id, value: SecureRandom.uuid %>

        <h5>Stammdaten</h5>
        <%= ff.fields_for "name[]", @name do |name_field| %>
            <div class="row p-3">
                <div class="input-field col l3 m12 s12">
                    <%= name_field.text_field :prefix, multiple: true %>
                    <%= name_field.label :prefix, "Titel" %>
                </div>
                <div class="input-field col l3 m12 s12">
                    <%= name_field.text_field :given, multiple: true %>
                    <%= name_field.label :given, "Vorname" %>
                </div>
                <div class="input-field col l3 m12 s12">
                    <%= name_field.text_field :family %>
                    <%= name_field.label :family, "Nachname" %>
                </div>
                <div class="input-field col l3 m12 s12">
                    <%= name_field.text_field :suffix, multiple: true %>
                    <%= name_field.label :suffix, "Suffix" %>
                </div>
            </div>
        <% end %>

        <div class="row p-3">
            <div class="input-field col l3 s12">
                <%= ff.select :gender, options_for_select([["Männlich", "male"], ["Weiblich", "female"]]) %>
                <%= ff.label :gender, "Geschlecht" %>
            </div>
            <div class="input-field col l3 s12">
                <%= ff.text_field :birthDate, class: "datepicker" %>
                <%= ff.label :birthDate, "Geburtsdatum" %>
            </div>
        </div>

        <h5>Kontaktinformationen</h5>
        <%= ff.fields_for "address[]", @address do |address_field| %>
            <div class="row p-3">
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :line, multiple: true %>
                    <%= address_field.label :line, "Straße und Hausnummer" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :postalCode, data: { reflex: "blur->Contact#plz_lookup" } %>
                    <%= address_field.label :postalCode, "Postleitzahl" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :country, disabled: true %>
                    <%= address_field.label :country, "Land", id: "country-label" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :state, disabled: true %>
                    <%= address_field.label :state, "Bundesland", id: "state-label" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :city, disabled: true %>
                    <%= address_field.label :city, "Ort", id: "city-label" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.text_field :district %>
                    <%= address_field.label :district, "Stadt-/Landkreis" %>
                </div>
            </div>
            <div class="row p-3">
                <div class="input-field col l2 s12">
                    <%= address_field.select :use, options_for_select([
                        ["Wohnsitz", "home"], 
                        ["Arbeit", "work"],
                        ["Vorübergehende Anschrift", "temp"],
                        ["Rechnungsadresse", "billing"]
                    ]) %>
                    <%= address_field.label :use, "Adressart" %>
                </div>
                <div class="input-field col l2 s12">
                    <%= address_field.select :type, options_for_select([
                        ["Nur Wohnsitz", "physical"],
                        ["Nur Postanschrift", "postal"],
                        ["Beides", "both"]
                    ]) %>
                    <%= address_field.label :type, "Adresstyp" %>
                </div>              
            </div>
        <% end %>
    <% end %>
    <%= button_tag "Patient anlegen", type: "submit", class: "btn waves-effect btn-block light-green" %>
<% end %>
```

The address and name are built in the `new` controller action with the custom `build` method provided by the gem. The `multiple: true` attributes on the text fields add the last `[]` field I needed on the inputs.
The only thing you have to do then is to add an `id` field to the `AttrJson::Models`, even if you don't fill something in cause Rails expects that the object you pass to `fields_for` responds to an `id` method to return the object's ID. I guess it's needed for the `child_index` property.
So just add this line to the models:
`attr_json :id, :integer`

Of course this id is empty, so there won't get any child index passed in, but the form helpers works anyway. This way I accomplished to get the desired structure: 

`patient[resource][name][][prefix][]`

Thanks again and maybe this helps someome in the future! :smile:

**Comment by jrochkind** [comment]
Right on, thank you for including your solution. I will close this issue now!

I do think the rails automatic/magic `assign_attributes` stuff gets really complicated and hard to get right, and at some point if it's giving you trouble is best abanoned for just making whatever structures make sense to you in request, and writing custom code for translating it to logic to create/update models.

**Comment by jrochkind** [comment]
> The only thing you have to do then is to add an id field to the AttrJson::Models, even if you don't fill something in cause Rails expects that the object you pass to fields_for responds to an id method to return the object's ID. I guess it's needed for the child_index property.

Even though you aren't using cocoon I wonder if including `AttrJson::Model::CocoonCompat` in your models would solve this? It might not though. It is confusing to figure out what's going on, ActiveRecord doesn't have a clear API for doing this with "unusual" objects (like ours) instead of *actual* AR associations which is what it expects, we're sort of trying to fake it out, which is again why at some point I'd just give up and write my own logic instead.

**Comment by jrochkind** [comment]
Hmm, we could write our own logic for `assign_attributes` that did the right thing for attr_json without trying to fake out ActiveRecord. 

    AttrJson.assign_attributes(model, attr_json_attributes_hash)

But I'm not really looking for more code to maintain either!
