### ISSUE TITLE
Error assigning polymorphic nested model via json_attributes=

### ISSUE THREAD

**Issue by machty** [jrochkind/attr_json#122]
I have a low level ActiveAdmin dashboard that only devs can use and it'd be nice in some cases to just edit the raw `json_attributes` jsonb field with a large text area input, but I can't figure out the proper way to do that without breaking something else (and I couldn't find documentation / prior issues regarding how to do that). Is it possible to do such a thing?

**Comment by jrochkind** [comment]
It should be! That was part of the design goal of this library to begin with. The json attribute column is the primary canonical source of info used by this gem -- you should be able to just edit it. 

Have you tried it and had problems? Can you, and let us know? 

The `json_attributes` column does already include ruby/model objects in it instead of json -- if you want the serialized json version, just call `to_json`, say `model.json_attributes.to_json`.  You can set `model.json_attributes=` with a value that is a pure json-able hash or a hash that includes ruby/model objects, either way should work fine.  You can also directly edit just elements, like `model.json_attributes["some_key"] = whatever`. 

Are you having difficulties?

I will also say that this goal -- to let you edit the json attributes column directly completely transparenty and have it just work -- has been coming into conflict with other people's desire to have the rails attributes synchronization ALSO just work transparently. If you are using the rails attribute wrappers, and you do edit the json attribute directly -- the rails attributes might get out of sync. 

These two goals kind of contradict each other. A future version of attr_json may make some different choices there, although I'll do my best to make migration smooth. I also can't promise there will ever be such a future version, but I've been thinking about it, and ways to get rails attribute sync to work better.

**Comment by machty** [comment]
Sorry for now providing specifics, here's what I'm doing:

I wanted to test if I could just do `model.json_attributes=` with a raw json, so I did the following:

```
irb> ip.json_attributes_json
{
  "strategy": "#<InventoryPromotionStrategy::GroupedPromotionStrategy:0x00007f9a91044498>"
}
```

OK, so the `json_attributes` has Ruby objects on it like you said, so I called `json_attributes_before_type_cast` and it gave me:

```
{
  "strategy": {
    "type": "InventoryPromotionStrategy::GroupedPromotionStrategy",
    "//": "redacted"
  }
}
```

Which I'm guessing does the same thing as `.to_json` (sorry, I can't check exactly what to_json does atm).

When I tried to assign this via `model.json_attributes` and save, I got 

```
AttrJson::Type::PolymorphicModel::TypeError: This AttrJson::Type::PolymorphicType can only include {InventoryPromotionStrategy::SimplePromotionStrategy, InventoryPromotionStrategy::GroupedPromotionStrategy
```

Perhaps the issue is with Polymorphic records? Here's my declaration

```
  STRATEGY_CLASSES = [
    InventoryPromotionStrategy::SimplePromotionStrategy,
    InventoryPromotionStrategy::GroupedPromotionStrategy,
  ].freeze
  attr_json :strategy, AttrJson::Type::PolymorphicModel.new(*STRATEGY_CLASSES)
```

**Comment by jrochkind** [comment]
Hmm, might be a bug in the Polymorphic classes of some kind.  Thanks for reporting it!

I can try to look at it, but if you have time to help out, it would speed up the process! 

If you could try it without the polymorphic type, and see if it works fine?

Then, especially if it does, if you could make a failing test case that could be PR'd to attr_json, demonstrating what I'm tentatively calling a bug with regard to this behavior and the polymorphic type? 

The polymorphic classes are somewhat "experimental" -- hopefully if it's a bug it will be easy to fix, not some flaw in the whole design!

**Comment by jrochkind** [comment]
It's also possible I'm totally wrong about it working with plain non-polymorphic models! Curious what you discover, if you have time to investigate further.

**Comment by machty** [comment]
Created PR #123

**Comment by machty** [comment]
FYI I love polymorphic nested models, and there are certainly very valid use cases for them. As referenced in my pseudo code above, I have an ActiveRecord object with a polymorphic "strategy" class that have completely different structures from each other, and in the absence of polymorphic nested models I'm not sure how to model it.

**Comment by jrochkind** [comment]
oh yeah I love em too, I"m just not shocked if I didn't make em work completely smoothly (yet?)!

Thanks! I'll try to find time to take a look soon. I have some thoughts! Thanks for your feedback and contribution!
