### ISSUE TITLE
Override of attr_json's

### ISSUE THREAD

**Issue by glebglazov** [jrochkind/attr_json#128]
Hey, thanks for a useful gem and support of it!

I have a question regarding overriding attributes: it there some particular reason we try to prevent it [here](https://github.com/jrochkind/attr_json/blob/v1.3.0/lib/attr_json/attribute_definition/registry.rb#L79) and [here](https://github.com/jrochkind/attr_json/blob/v1.3.0/lib/attr_json/attribute_definition/registry.rb#L89)? Would it make sense to allow overrides when passing an option `override: true`? 

Asking cause in our case we have modules that include batch of `json_attr`'s though we want override defaults for some of the models. Will be glad to work on the addition of a feature.

Thanks in advance!

**Comment by jrochkind** [comment]
I can't recall for sure. Possibly I just didn't know what would happen, if it would actually be succesful or not. And rather than try to cover all possible places it could go wrong in test cases, I just disallowed it.  Just in general, the code here is complicated enough already, I sometimes try to keep it from getting more complicated by limiting edge case possibilities. 

Also, if you are trying to override in a sub-class to have a different definition, I think it would violate the [Liskov substitution principle](https://stackify.com/solid-design-liskov-substitution-principle/).  If you have an ordinary ActiveRecord subclass, I believe you can't ordinarily redefine an attribute to be different than the superclass -- because it's normally backed by the same underlying table/column, right?

What is your interest/use case?

**Comment by glebglazov** [comment]
Our use case is the urge to 1) keep attributes of a feature in modules to ease inclusion in specific implementations 2) to override `default` without hurting LSP, cause in our case we want to preserve interface of superclass.

I'll give an example, let say we're trying to enrich several models with frequently changing interface of :
```ruby
module ContactAttributes
  def self.included(base)
    base.attr_json :has_phone, :boolean, default: false
    base.attr_json :phone, :string
  end
end

class School < ApplicationRecord
  include AttrJson::Record
  include ContactAttributes
end

class Hospital < ApplicationRecord
  include AttrJson::Record
  include ContactAttributes
end
```

So I start to use those models to render form with defaults: so when creating both School and Hospital by default we have checkbox controlling `has_phone` disabled and thus not rendering `phone`, when `has_phone` is checked, we start to render `phone` input, everything works fine this far. Problems start when I want to make `has_phone` default to true for hospitals as it's not possible at the moment. 

Earlier we've being using `store_attribute` gem and what we've done is separate wrapper for overrides which will only allow to set new `default`, so that we would not (hopefully) break LSP for a serialized column.

Of course we could go with some crazy stuff like
```ruby
class AttributesWithCustomizableDefaults < Module
  def initialize(**options)
    @options = options
  end

  def included(base)
    base.instance_exec(options) do |custom_default:|
      attr_json :attribute, :integer, default: custom_default
    end
  end
end

class Model < ApplicationRecord
  include AttributesWithCustomizableDefaults.new(custom_default: 2)
end
``` 

This helps me stick to interface of whatever I'm trying to model here, but it's really an overkill IMO :)

Additionally, Rails attributes API allows me to do something like that:
```ruby
class Model < ApplicationRecord
  attribute :some_attribute, default: 5
end
``` 

Thanks for the answer and let me know what you think

**Comment by jrochkind** [comment]
Thanks for explaining!

Hm, I'm not sure your second solution is that crazy. But you could also make it a method instead of a module at all. Something like:

```
class AttributesWithCustomizableDefaults
  def self.apply(base, has_phone_default: false)
           base.attr_json :has_phone, :boolean, default: has_phone_default
           base.attr_json :phone, :string
  end
end

class School < ApplicationRecord
  include AttrJson::Record
  AttributesWithCustomizableDefaults.apply(self)
end

```

It occurs to me you don't *really* want to override the value -- you want to "override" it _right_ after setting it, it's not like you have a superclass with one value and a subclass with another. That you need to "override" it is just a consequence of trying to be like "first I apply a module, but then I immediately reset what the module set to be what I *really* want it to be"

In fact, you aren't even *really* applying the module at all, you're just using it as a hook for `def included`. I think maybe my above suggestion is very similar but maybe actually even simpler?

**Comment by glebglazov** [comment]
> In fact, you aren't even really applying the module at all, you're just using it as a hook for def included
Yeah, thought of a case when we do have some methods around attributes as well, but haven't managed to express it well enough :) This way it could come in handy in terms of Ruby-like interfaces inclusion

Though we could use something like 
```ruby
class AttributesWithCustomizableDefaults
  module Interface
    # instance methods
  end

  def self.apply(base, has_phone_default: false)
    base.attr_json :has_phone, :boolean, default: has_phone_default
    base.attr_json :phone, :string
    base.send :include, Interface
  end
end

class School < ApplicationRecord
  include AttrJson::Record
  AttributesWithCustomizableDefaults.apply(self, has_phone_default: true)
end
```
and eventually achieve same result

Though API wise it would be less attractive for us cause in our case we do have around 6 of those `School`'s and we're mixin in 5 those 'shared attributes' modules via shared interface

```ruby
module InstitutionInterface
  include ContactAttributes
  include RatingAttributes
  # 3 includes more

  # class methods
  # instance methods
end
```

then it's simply included into "institution" and in 1 or 2 cases (`attr_json`) we do override `default` option:
```ruby
class School < ApplicationRecord
  include InstitutionInterface

  serializable_attributes do |s|
    s.override :has_phone, default: true
  end
end
```

The idea I have now is to go with combo solution which will include having a list of attributes definitions :
```ruby
module InstitutionAttributes
  def apply(
    base,
    has_phone_default:
    # couple defaults kwargs here as well
  )
    # Instead of 5 "shared attributes" modules with decoupled attributes we could define all of those here 
    # so that we would not need to do N .apply's of something like ContactAttributes 
    # in M 'institutions' 
    base.attr_json :has_phone, :boolean, default: has_phone_default
    base.attr_json :phone, :string

    # Interfaces of such groups of attributes could reside in modules as well
    base.send :include, ContactAttributesInterface
  end
end
```

So we end up with single `.apply` in each 'institution'

**Comment by jrochkind** [comment]
I think I'm going to close this for now -- I see your use case, and how it could be more convenient with changes in attr-json, but to keep attr_json sustainable and low-maintenace on my end (so it will keep working for all y'all!), I am very cautious about code changes, and since you've found a good workaround for now, I'm going to avoid this one for now. 

Btw: Another workaround, you could probably go into the json_attr_registry data structure yourself to mutate it to *remove* the previous registration -- then attr_json couldn't complain about a previous registration you were overwriting, it would be erased, and let you do it again!  I don't have exactly the code needed to do this in front of me, but I believe it should be possible. 

Thanks for using attr_json and getting in touch! Glad you found a way to keep it working for you!
