### ISSUE TITLE
Compound data dynamic

### ISSUE THREAD

**Issue by danieldocki** [jrochkind/attr_json#130]
Based on an attribute the model changes, is there a way to do this? example: 

```ruby
class Model < ApplicationRecord
  include AttrJson::Record

  attr_json :theme, :string, default: 'default'
  attr_json :theme_settings, Object.const_get("Themes::#{theme.capitalize}").to_type
end
```

or maybe inside the `AttrJson::Model` to have dynamic attributes, depending on the chosen theme.

**Comment by jrochkind** [comment]
Hey, thanks for checking in

If I understand right, you want to have different types on an attr_json attribute, that differ on a per-instance basis. 

You can't do that at present. Thinking about it, I'm not sure if it's a good idea from an Object-Oriented Design perspective -- I maybe feel like all instances of Class should have the same type, a caller should know what data type is in an attribute based on the Class alone. And what would happen to an existing object if you change the `theme` attribute, when it has existing data that now is invalid because the wrong type for the new theme?

But whether it is a good idea or not, it would take some pretty significant refactoring to make possible, and at present I don't think it's in the plans. 

There are some things you could do instead. You could create a sub-class for each theme (presumably using [Rails single-table inheritance](https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html)), something like:

```ruby
class RedModel < Model
   attr_json :theme_settings, Themes::Red.to_type
end

class GreenModel < Model
   attr_json :theme_settings, Themes::Green.to_type
end
```

That should work out okay I think -- I do similar things using Rails single-table inheritance in my apps. 

You could probably even define them dynamically. This is something I've thought about, and it should work, but I could see it getting a bit confusing to debug maybe, and haven't tried it to smooth out all the rough edges myself. Not totally sure if it's a good idea:

```ruby
["Green", "Red"].each do |theme_name|
   ThemeModels.const_set(theme_name, 
      Class.new(Model) do
         attr_json :theme_settings,  Object.const_get("Themes::#{theme_name}").to_type
      end
    end
end
```

Or, for a different approach, if you could make theme settings types that were subclasses of each other, allow the superclass, but use a validation to ensure 

```ruby
class ThemeSettings
  include AttrJson::Model

  attr_json :theme_name
end

class RedThemeSettings < ThemeSettings
    attr_json :shade_of_red, :integer
end

class BlueThemeSettings < ThemeSettings
   attr_json :transparency, :boolean
end

class Model < ApplicationRecord
  include AttrJson::Record

  THEME_SETTINGS_CLASSES = {
    "red" => RedThemeSettings,
    "blue" => BlueThemeSettings
  }

  attr_json :theme, :string, default: 'default'
  attr_json :theme_settings, ThemeSettings.to_type

  validate :theme_settings_match

  def theme_settings_match
      unless theme_settings.class == THEME_SETTINGS_CLASSES[theme]
               errors.add(:theme_setting, "must be #{THEME_SETTINGS_CLASSES[theme]} to match theme")
      end
end
```

Although I guess that last one won't necessarily automatically cast the way you want, which could be inconvenient. 

I'm not really sure which, if any, of these approaches would be best. I'd be concerned with keeping it simple... making this stuff get complicated tends to bite you later. 

Hope this gives you some ideas of some things you might do!

**Comment by jrochkind** [comment]
Oh, I realized for some of those solutions you are going to want the polymorphic types feature in attr_json -- that may get you a lot of what you want actually? 

https://github.com/jrochkind/attr_json#polymorphic-model-types

I'm not totally sure the best way to do what you are looking for. If you experiment with anything let us know what you discover!

**Comment by danieldocki** [comment]
Amazing these ideas, will help me a lot to do what I need, in the next few weeks I will try, I think with subclasses or with polymorphic types feature can be the way.

Thank you for the tips @jrochkind

**Comment by jrochkind** [comment]
Great! I realized that some of those ideas might not actually work, I was just brainstorming... if you hit a roadblock, don't assume it's your fault, some of my ideas might be deadends, but let us know what you find!

I think maybe polymorphic alone might get you close enough to what you need, although not exactly what you asked for.
