### ISSUE TITLE
Support for encryption

### ISSUE THREAD

**Issue by JensDebergh** [jrochkind/attr_json#141]
Hi!

I'm loving this gem and use it extensively through some core components of my product.
We're workings towards integrations and want to save some arbitrary data based on the integration a user chooses.

This data can vary from sensitive data like `access_tokens` to just `ids` for specific resources in a system.

I tried setting up `attr_json` & `lockbox` together but they do not seem to work together properly. 

I was wondering if there is a way to make `attr_json` & `lockbox`/ `encrypts` rails 7 work together nicely.

**Comment by jrochkind** [comment]
Hi thanks for getting in touch!

I think it would take some work, because of the way attr_json needs to make a copy of the attribute in the JSON hash.  The attr_json code is already a bit convoluted.  

I'm looking to find some time to refactor a bit to simplify (now that we can drop support for old Rails; there were some improvements to attributes API around Rails 5.0 I think, that came after the first version of this!), and want to look to [jsonb_accessor](https://github.com/madeintandem/jsonb_accessor) for patterns when I do.  jsonb_accessor is pretty good, and in some ways has a cleaner implementation -- but doesn't handle *nested* models like we do here. 

I'd be curious if encrypted attributes work with jsonb_accessor -- want to check it out and report back? (You'd want to actually look at the json hash itself and confirm the attributes are *really* encrypted in the DB). If you don't need nested models you might just want to use it, but either way I'm curious for the report back, because if it does work, then perhaps it would show a path to making attr_json work too. 

Back to attr_json....  you *could* just mark the whole json(b) column/attribute encrypted with standard Rails or lockbox, and I *believe* that should work fine (let me know if it does/doesn't?), although that may be inconvenient (you aren't really going to be able to DB query on individual attributes at all ever) and not what you're looking for.

**Comment by jrochkind** [comment]
Hi, I'm going to close this for now due, but if you comment again and want to discuss/investigate more, I can re-open it!  I am interested in the results of any further investigations you do.
