### ISSUE TITLE
Removing / Renaming attributes

### ISSUE THREAD

**Issue by JensDebergh** [jrochkind/attr_json#154]
Hi! 

I'm using this library extensively in one of my apps and love it, now I've reconsidered some of the attributes I defined earlier which already has production data and I was wondering if there is a sample way to cleanup / rename attributes.

If I remove the the defined attribute and the old `json_attributes` hash still contains that column the library throws an error for the method that obviously is not defined anymore.

Thank you in advance!

Kind regards
Jens

**Comment by jrochkind** [comment]
Did the `unknown_key` config work well for you, then?

I feel like it actually shouldn't be too hard to remove keys from the json column itself, but if you have a solution that's working well for you we don't have to go into it!

I don't really need or want tips for `attr_json` at all, nothing required. Since you ask, I did set up Github Sponsors for my rubyland.news project though... https://github.com/sponsors/jrochkind
