### ISSUE TITLE
AttrJson::Model undefined method `validates_uniqueness_of`

### ISSUE THREAD

**Issue by Ancez** [jrochkind/attr_json#200]
Hi, I'm unsure how best to validate uniqueness of a field on an attr_json model.

I think the ideal implementation would look like this:
```ruby
class Main
  include AttrJson::Record
  include AttrJson::NestedAttributes

  attr_json :fields, MainField.to_type, array: true
end

class MainField
  include AttrJson::Model
  include AttrJson::Model::CocoonCompat
  
  attr_json :name, :string
  attr_json :order, :integer
  
  validates_uniqueness_of :order
end
```

But the uniqueness validator doesn't work `undefined method 'validates_uniqueness_of' for MainField:Class`.

Instead, I had to validate the order uniqueness in the `Main` model via a custom method validator i.e.
```ruby
class Main
  # existing code...
  validate :fields_order_uniqueness
  
  def fields_order_uniqueness
    # logic
  end
end
```
 
nb. using `validates_with` doesn't work either.

This might be a potential feature request depending on what others think.

Thank you for your time, and I look forward to hearing your thoughts.

**Comment by jrochkind** [comment]
Hi, thanks for trying out attr_json and getting in touch!

I can't think of a good way to do this, since validating uniqueness requires going to the database to check, and the `include AttrJson::Model` model itself doesn't actually know that it's in the database, or where in the database. 

So we can't really take advantage of built-in Rails classes. We'd have to write our own custom implementation and deliver it. And I'm cautious about doing that, or encouraging it, as going to the DB to validate uniqueness like this can be a performance issue too. 

Did you figure out a way to do it with your own custom method?  If so, would you like to share the implementation here for others who are interested?  I think that's the first step!  Then if it works out for people we could consider taking the code into the gem. But my inclination right now is that this is not something AttrJson will support. 

(Note: I beliveve `validates_uniqueness_of` should work fine on `AttrJson::Record` already though, we're only talking about the `Model`).

**Comment by jrochkind** [comment]
Hi, I'm going to close this for now; it's not currently in the plan to address. If you have more comments or thoughts, feel free to comment on this ticket, or to open up a Discussion. Thanks for trying out attr_json!
