### ISSUE TITLE
Default values aren't being persisted

### ISSUE THREAD

**Issue by stevenharman** [jrochkind/attr_json#26]
I am interested in using `AttrJson` to store "notification settings" (think, subscribed/unsubscribed to various email, push notifications, etc...). As a very simple case, I have something like the following set up

```ruby
class User
  include AttrJson::Record
  include AttrJson::Record::Dirty
  include AttrJson::Record::QueryScopes

  attr_json :subscribed_to_weekly_report, :boolean, default: :true, container_attribute: :notification_settings
end

class AddNotificationSettingsToUsers < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :notification_settings, :jsonb, default: {}
    add_index :users, :notification_settings, using: :gin
  end
end
```

The default value is present when I fetch back a record that's not yet had the key set, or when I create a new instance via `User.new`. But in neither case is the default value persisted back to the db upon `user#save`. That seems... odd. I even added dirty tracking to see if that would do it, but it's the same behavior.

```ruby
u = User.new
#<User> { notification_settings: { "subscribed_to_weekly_report: => true } }
u.save!
# INSERT INTO "users" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"
#<User> { created_at: <DateTime>, updated_at: <DateTime>, notification_settings: { "subscribed_to_weekly_report: => true } }
```

I have to set the attribute to a non-default value (e.g., `false` for the boolean attribute I've setup above) and then save. At which point it's persisted. And setting it back to `true` and saving then persists that value.

Is this expected? Am I doing something incorrectly?

Thank you.

**Comment by jrochkind** [comment]
That definitely doesn't sound right. I wonder if it's a bug specifically related to boolean values. I will try to look into it. 

If you wanted to try to create a failing test in a PR, that would be helpful and a head start -- but not required, I'll look into it either way.

**Comment by jrochkind** [comment]
oh also, can you tell me what version of Rails just in case?

**Comment by stevenharman** [comment]
Sure. Rails 5.2

**Comment by jrochkind** [comment]
Aha, I did reproduce on travis when I added a test. 

It is specifically a problem with _boolean_ attributes it looks like, which i hadn't tested.  Defaults seem to work reliably for other types, just not boolean. 

Weird that I don't seem to be able to reproduce on my dev machine, just on travis -- the test I added passed on my dev box, and I was shocked to see it fail on travis.  

Anyhow, now I need to figure out what's going on and hopefully find a way to fix it. 

Thanks for taking it for a spin reporting the problem. I could suggest various workarounds (like using AR callbacks instead of attr_json default), but I'm not really sure the nature of the problem, or if it only effects defaults or there will be other problems with booleans. I will investigate more!

**Comment by jrochkind** [comment]
Wait, sorry, deleted that last comment. 

That was my user error, I'm actually not succesfully reproducing your problem yet. I'll try harder to do exactly what you are doing, but if you want to put a full rails app demonstrating the problem in github, or PR a failing test case, or anything else with runnable code demonstrating the failure, it would be helpful! (But not required, I'll keep digging).

**Comment by jrochkind** [comment]
oh wait, I do now understand what you're reporting better now. OK, i'll keep digging. Hmm, this might be tricky. 

Thanks for taking it for a spin and reporting!

**Comment by jrochkind** [comment]
gah, yeah, this is a consequence of how I did defaults. I will try to figure out how to fix it, hmm.

**Comment by stevenharman** [comment]
@jrochkind thanks for digging in. And sorry it's turning out to be tricky. It sounds like you've got a handle on it, but if you still need something reproducible, I can try to get a failing test together. Else, let me know if you need more info.

Thanks!

**Comment by jrochkind** [comment]
thanks, yeah, i've got a failing test written now, just got to dig into AR internals to understand what's going on and why it's not what I expected, heh.

**Comment by jrochkind** [comment]
Hmm, I've found a way to maybe make it work _more_ of the time, but it's pretty tricky dealing with AR with regard to this stuff. I can't believe I didn't notice it wasn't working like this already, I would have expected it to, thanks for pointing it out. 

Can you talk about about your use case, and what problems this will cause you as is?

As it is, I believe if you have _any_ `attr_json` in the same `container_attribute` that you DO set manually (by any means), then the defaults will all be saved to db. But if it's _only_ defaults, nothing will be saved to db for that column, AR at the moment thinks there have been no changes to save.

**Comment by jrochkind** [comment]
you can also of course use normal AR migration/db defaults, I wonder if this would work for you:

    add_column :users, :notification_settings, :jsonb, default: {"subscribed_to_weekly_report => true}

**Comment by jrochkind** [comment]
I _may_ have found a way to change it in all cases, but now I'm starting to get confused about which is the better behavior!  

Maybe if you instantiate a record and make no other changes, you don't a write to the db to be forced to write the defaults there?  I may experiment more with what AR does in similar situations without my code. 

But still interested in your use cases!

**Comment by jrochkind** [comment]
Okay, so right now.... notice that your migration with `default: {}` is neither recommended by docs nor necessary (although it doesn't hurt).  You don't need any default there. 

In the situation where you supply no default in the migration, and no defaults in `attr_json` -- if you create a record without assigning any values to `attr_json` at all, your container attribute remains `null`/`nil` in the db, not the empty hash. Or you can set it to the empty hash yourself, or whatever. It's up to you, but you can have a distinction between nil and the empty hash if you want. 

With the way I've found to make it work how you expect for your case, this will go away -- even if you have no attr_json defaults, saving a model with any attr_json's will result in an empty hash to the container attribute, never nil. 

I'm not really sure if this is a problem?

I'm also not really sure I understand _how_ I tricked AR into doing what we want in this ticket either, I don't totally trust it.

**Comment by stevenharman** [comment]
> a default value of the empty hash always seemed better/advised b/c it made querying the data more consistent - not having to deal with null. Though... perhaps even that's unnecessary?

It seems I might have been right to default to the empty hash. A `jsonb` column with `nil` value must be specially accounted for when querying. Whereas the contains operator (`@>`) handles an empty hash as you'd expect:

```sql
SELECT * FROM "users" 
  WHERE NOT("notification_settings" @> '{"subscribed_to_weekly_report":false}')

/* rows with an empty hash are returned. Rows with nil are not */
```

**Comment by jrochkind** [comment]
A) Your use case makes sense, I get why you need/want this. 

B) Yes, that makes sense for querying. Not everyone has gotta query, but it does make sense. In general, I'm trying to keep this thing as open and non-assumption about what you want to do as I can, to make it a suitable flexible lower-ish-layer. 

C)  You _could_ actually do an AR migration db-level default to `default: {subscribed_to_weekly_report: true`, I tested that and it works in Rails 5.2 at least. It serializes to JSON and puts that string as the db default, and everything else in attr_json works. But I'll assume this is not ideal and you understandably would prefer to keep everything together. 

D) 

>To be clear, I absolutely think that User.new should not, ever, write to the DB. But, I would expect that User.create would write to the DB, and that any default values I've setup for the column are persisted. 

Right, I understand and am on the same page. the question is:  if you _don't_ have any attr_json defaults, and _don't_ have a migration-db default to `{}`, when you do Record.create, should your container attribute be forced to be `{}`, or should it be allowed to be `nil`, might some users want to allow it to be `nil` (ie entirely `NULL` in the db, no json value at all)  and have `nil`  and an empty hash be different things?

Do you follow? I'm not sure. Interested in your opinion if any. But I am reluctant to take that option away. But I think there's probably a solution. 

Oddly, for reasons I mostly but don't _entirely_ understand, what makes this do what _you_ want is putting in an AR attributes-API default of `{}`.  Because AR ends up storing the `{}` somewhere in it's depths it uses for change-tracking, and then realizes that the hash-with-defaults is not the same as `{}`, and the column is dirty and needs to be persisted.  Which otherwise there's no good API to access from where the attr_json code is currently.  The migration/db-level default is _not_ enough. And if the AR attributes-API default _is_ there, you wouldn't need the migration/db-level default, it would always end up being an empty hash anyway. 

So what I'm thinking is I need an additional argument to `attr_json` that controls whether there is an AR-level (not db) `{}` default enforced, or not. And it will probably default to doing what will make things how you want, but still be optionally settable for the 'old' way. 

It's also possible I don't need the configuration, and should just force AR-level default to `{}`. 

I appreciate your conversation and feedback!

**Comment by jrochkind** [comment]
(Oh, and there was something _else_ I had to fix to make the AR-level-default-to-{} work too, btw.)

**Comment by stevenharman** [comment]
_Side bar:_ I just stumbled across https://github.com/byroot/activerecord-typedstore, which might be of interest. At least there might be some tips, tricks, or ideas in the implementation that could inspire implementation of `attr_json`. 😄

**Comment by stevenharman** [comment]
Getting back to [your post from yesterday](https://github.com/jrochkind/attr_json/issues/26#issuecomment-387888560), I'd agree with what you have there. A default of `{}` makes sense, so long as there's a way to allow a `nil` default I suppose.

> You could actually do an AR migration db-level default to default: {subscribed_to_weekly_report: true} [...] I'll assume this is not ideal and you understandably would prefer to keep everything together.

The other problem is I'd need to change the db default every time we add a new kind of notification setting (e.g., a new email, or push notification). I'd rather have the default defined in the AR model, right next to where I'm declaring the attribute. In fact, using the following, which all comes out of the box in modern Rails, mostly gets it done:

```ruby
  attribute :notification_settings, :json, default: { subscribed_to_weekly_report: true }
  store_accessor :notification_settings, :subscribed_to_weekly_report
```

This only works for simple cases and breaks down if need to nest data, or have compound/custom types. Or if I want/need to type-cast the values. Which is what `AttrJson` is for, I suppose. Or `activerecord-typed-store` if I only need/want the type casting. And of course, I have to hand-roll all of the querying.

**Comment by jrochkind** [comment]
Yep, I'll get it working one way or the other. Into some investigations to understand what's going on and the implications better. Thanks for your patience, I'm trying to be really intentional with this gem, cause I want it to be really solid, cause I plan to build other layers on top of it.

**Comment by jrochkind** [comment]
I can now make it work, but it messes up my Dirty implementation for reasons I don't understand yet. 

I _think_ that my previous implementation actually _wouldn't_ let you set the container attribute to nil anyway. I had that in mind as a use case, but apparently never tested it and it wasn't possible anyway, so once I confirm that for sure in master branch, that's not a concern.

**Comment by jrochkind** [comment]
The bizarre thing is when I apply my _own_ under-the-hood `attributes ... default: -> { {} }` under the hood... and then use the stock AR dirty stuff.... the "original value" of the container attribute switches from empty hash to nil. Like it's the _opposite_ of what I expect. 

But if I account for that, all my dirty tests pass again... so I guess I'll just accept it and not do more AR code archeology. 

@stevenharman are you interested in looking over the PR to help out?  I have nobody regularly doing code review.
