### ISSUE TITLE
Document/support a way to have a free-form json field

### ISSUE THREAD

**Issue by onomated** [jrochkind/attr_json#32]
This would be great for caching data that may not always have a predetermined form such as data from a third party api, or data that may take different forms based on other "type" context in the record.
A simple implementation would be to allow vanilla `ActiveModel::Type::Value` entries such as:

```ruby
  class JsonHash < ActiveModel::Type::Value
    include ActiveModel::Type::Helpers::Mutable

    def deserialize(value)
      if value.is_a?(Hash)
        value.with_indifferent_access
      else
        value
      end
    end
  end
```

**Comment by TylerRick** [comment]
I was just about to suggest this feature myself (assuming we're talking about the same thing)... :)

I'd be curious to learn a little more detail about your use case(s). If I'm not mistaken, you can already easily do that **_without_** `attr_json` simply by adding a `jsonb` column for your attribute (say, `data_from_some_api`) and using it directly! :)

How were you envisioning using hashes in relation to `attr_json`? For comparison, here's kind of what I was thinking, so we can figure out if we're talking about the same feature...

---

I'd like to have a way to nest well-typed, structured `AttrJson::Model` types inside of a hash-like container, kind of like how it already lets you have an _array_ of `AttrJson::Model`-typed objects within (and nested in any way/at any depth) your JSON attribute.

For example, you could have a hash of pet names to data about each pet, or category names to settings for each category (like I was trying to do in https://github.com/jonhue/notifications-rails/issues/43)...

```ruby
class Settings
  include AttrJson::Model
  attr_json :enabled, :boolean, default: true
  # ...
end

class User < ActiveRecord::Base
  attr_json :notification_settings, Types::HashWithValuesOf(Settings.to_type)
end
```
```ruby
user.notification_settings[:likes].enabled = true
user.notification_settings[:promotions].enabled = false
```
As a convenience, it could let you access keys with Hash-style `hash['key']` or object-style `object.key` (just like you can in JavaScript). It could also allow indifferent access by default (by string or symbol keys).

(It could also _optionally_ return an instance of the sub-type by default for keys that don't exist in the hash yet (`just like if you had used Hash { Settings.new }`). But would that set the key too, so that changes to the returned object get saved in the hash?)

I would also propose allowing an alternate syntax for making something an array type... Instead of:
```
attr_json :numbers, :integer, array: true
```
I think I'd prefer to be more explicit about the "array of" relationship, so I can say, literally, this attribute's type *is an array _of_ [other type]*:
```
attr_json :numbers, [Types::ArrayOf(:integer)]
```
That would make a nice complement to the hash type...

WDYT?

---

Maybe you were more thinking of using a Hash like a primitive type, alongside other attributes in a container, like this?:

```
attr_json :favorite_number, :integer
attr_json :other_data, :hash
```
Is that not already possible?? (haven't checked)

**Comment by jrochkind** [comment]
> attr_json :other_data, :hash

Yes, I think that's what was desired. 

Not already possible, there is no registered type `hash` provided by ActiveRecord/ActiveModel, and no special 

Although actually it might be possible as `attr_json :other_data, ActiveRecord::Type::Json.new`, anyone want to try it?  (And it _might_ magically already be possible as `attr_json :other_data, :json`, try that too?)

**Comment by onomated** [comment]
> I'd be curious to learn a little more detail about your use case(s). If I'm not mistaken, you can already easily do that **_without_** `attr_json` simply by adding a `jsonb` column for your attribute (say, `data_from_some_api`) and using it directly! :)

@TylerRick Yes that is correct.  You can simply use a `jsonb` column for unstructured json data. 
 
> How were you envisioning using hashes in relation to `attr_json`? For comparison, here's kind of what I was thinking, so we can figure out if we're talking about the same feature...
> 
> I'd like to have a way to nest well-typed, structured `AttrJson::Model` types inside of a hash-like container, kind of like how it already lets you have an _array_ of `AttrJson::Model`-typed objects within (and nested in any way/at any depth) your JSON attribute.
> 

@TylerRick In my case I had a single jsonb column which had my predefined json fields with one of the fields being a hash of translated strings from a 3rd party source without knowing exactly which languages I would get translations back for in the format `{'en' => 'English translation', 'es' => 'Spanish translation'}`.  I could define an `AttrJson::Model` subfield with fields for every single possible language key, but that would be a hassle to maintain/keep up with the growing list of supported languages in the 3rd party service.  So I wanted the free-form hash in this case.

> For example, you could have a hash of pet names to data about each pet, or category names to settings for each category (like I was trying to do in [jonhue/notifications-rails#43](https://github.com/jonhue/notifications-rails/issues/43))...
> 
> ```ruby
> class Settings
>   include AttrJson::Model
>   attr_json :enabled, :boolean, default: true
>   # ...
> end
> 
> class User < ActiveRecord::Base
>   attr_json :notification_settings, Types::HashWithValuesOf(Settings.to_type)
> end
> ```
> 
> ```ruby
> user.notification_settings[:likes].enabled = true
> user.notification_settings[:promotions].enabled = false
> ```
> 
> As a convenience, it could let you access keys with Hash-style `hash['key']` or object-style `object.key` (just like you can in JavaScript). It could also allow indifferent access by default (by string or symbol keys).
> 
> ```ruby
> user.notification_settings['followers'].enabled = true
> user.notification_settings.newsletter.enabled = false
> ```
> 
> (It could also _optionally_ return an instance of the sub-type by default for keys that don't exist in the hash yet (just like if you had created the hash using `Hash { Settings.new }`). But would that set the key too, so that changes to the returned object get saved in the hash?
> 
> ```ruby
> settings_for_category = user.notification_settings[:likes]
> settings_for_category.enabled # => true
> settings_for_category.enabled = false
> user.notification_settings[:likes].enabled # => false
> ```
> 
> )

Interesting.  All use-cases I didn't envision/think off.  I've used attr_json now in two different rails apps and haven't had the urge for keyed hash accessors on my `AttrJson::Model` fields, the dot accessor has been intuitive since these feel like class type definitions in my case.  

> I would also propose allowing an alternate syntax for making something an array type... Instead of:
> 
> ```ruby
> attr_json :numbers, :integer, array: true
> ```
> 
> I think I'd prefer to be more explicit about the "array of" relationship, so I can say, literally, this attribute's type _is an array _of_ [other type]_:
> 
> ```ruby
> attr_json :numbers, Types::ArrayOf(:integer)
> ```
> 
> (and/or simply:
> 
> ```ruby
> attr_json :numbers, [:integer]
> ```
> 
> )
> 
> I think that would be a nice complement to the new hash type...
> 
> Other options for indicating a hash type:
> 
> ```ruby
>   # Values can be anything; keys can be anything (free-form hash)
>   attr_json :settings, Types::Hash
>   attr_json :settings, :hash
> 
>   # Values are Settings objects; keys can be anything
>   attr_json :settings, Types::Hash(Settings.to_type)
> 
> 
>   # If you want to specify that they keys should be strings...
>   attr_json :settings, Types::Hash(:string => Settings.to_type)
>   # How would it even work with keys of other types?
>   attr_json :settings, Types::Hash(:custom_type => Settings.to_type)
> ```
> 
> WDYT?

I defer to @jrochkind comments on the complexity of implementing this.  I have been able to meet all my use cases with the current set of features outside of the one-off cases where I wanted a freeform hash field. And this includes an app that I migrated data from mongo to postgres btw.

> Maybe you were more thinking of using a Hash like a primitive type, alongside other attributes in a container, like this?:
> 
> ```ruby
> attr_json :favorite_number, :integer
> attr_json :other_data, :hash
> ```
> 

Yes this is my scenario I described above.  

@jrochkind, you can use `:json` as a type without any ceremony today.  The only "advantage" of the implementation I suggested earlier is that the deserialized hash is an `ActiveSupport::HashWithIndifferentAccess` so I can access my fields as strings or symbols.  Using the built-in `:json` type always returns hashes with string fields.  I registered the type with active record in an initializer.  Notice it has to be registered as an `ActiveRecord::Type` (as opposed to `ActiveModel::Type`) based on our conversation in #30:

```ruby
ActiveRecord::Type.register(:hash, JsonHash)
```
 and use in model definitions as:

```ruby
...
attr_json :title_translations, :hash
```

**Comment by jrochkind** [comment]
Thanks @onomated 

> The only "advantage" of the implementation I suggested earlier is that the deserialized hash is an ActiveSupport::HashWithIndifferentAccess so I can access my fields as strings or symbols. Using the built-in :json type always returns hashes with string fields.

If you use `:json` type, it works exactly like an ordinary ActiveRecord ("top-level") json-type column. You can _set_ with symbol keys, and it works, but you have to _read_ with string keys, yep. Since that's just exactly like the built-in "ordinary" AR json or jsonb types, that seems appropriate to me, and not worth adding extra code to maintain to attr_json. 

However, the amazingness of the ActiveRecord/Model Type api that attr_json is based on means that you can always create and use your own types, as @onomated has done, and that should be supported. 

I _am_ going to make a PR with tests proving that json/jsonb work, and docs suggesting it (since I didn't think of it i myself at first!). And then close this ticket with that.  When I get around to it.

Thanks all!

**Comment by jrochkind** [comment]
@nhemsley kindly verified this is already possible simply with:

    attr_json :whatever, ActiveModel::Type::Value.new

See #56 and #61. Will merge those to have tests verifying this remains true, and docs pointing it out --but no code changes required, you can already do this in the attr_json you've already got!
