### ISSUE TITLE
Question: Easy way to update dynamic generated nested paths?

### ISSUE THREAD

**Issue by quadur** [jrochkind/attr_json#50]
Hi, 
Im using attr_json to store documents that have deeply nested fields, is there a way to update specific fields having an path of keys in an array or a specific hash?

For example, lets say we have a "path" array ``["summary", "products", "prices"]`` that we want to set to ``[1,2,3]``, if it were a static action it would be easy: 
```
@document.summary.products.prices = [1,2,3]
@document.save
```

I tried to generate a nested hash and using a plain old .update like this: 
```
d = {"summary" => {"products" => {"prices" => [1,2,3]}}}
@document.update(d)
```
But (as expected) it sets the specific path and resets the rest of the ``@document`` to defaults.

Right now Im just getting the whole document content as_json, changing the specified value using some dig magic and doing a ``@document.update`` with the whole JSON. It works but I would like to know is there a way to do this "properly"?

**Comment by jrochkind** [comment]
Hmm, I'm not completely sure what's going on, if you'd like to give a complete code sample of your model(s) that might be helpful. 

But does this work/help?

    @document.summary = @document.summary.merge({"products" => {"prices" => [1,2,3]})

Except there might be something else in the `products` key you are overwriting there and don't want to. 

The first thing is verifying that just updating the hash as a hash works -- I _think_ it should. It won't necessarily be type-cast in-memory right away, but should be if you access `summary` again, or when you save the record. 

Then, if so, it's just any standard ruby for updating a hash with a keypath, there's nothing built into attr_json to do it, but it's just ruby. 

Perhaps you want to just write your own code to turn a directive hash like `{"summary" => {"products" => {"prices" => [1,2,3]}}}}` into `@document.summary.products.prices = [1,2,3]`. Hmm...

```ruby
class Util
  def self.path_set(obj, path_instruction)
     path_instruction.each_pair do |key, value|
        if value.kind_of?(Hash)
            path_set(obj.send(key), value)
        else
            obj.send("#{key}=", value)
        end
     end
end
```

That's just off the top of my head without trying it. 

There may also be existing ruby gems to do this sort of thing. 

With this _particular_ example... my first reaction is I wouldn't personally do products and prices with attr_json instead of a normalized db schema, but you might have reasons it makes sense. 

My own use cases usually involve updating the entire structure for a particular `attr_json` at once, from a form. 

Hope this helps?

**Comment by jrochkind** [comment]
Currently no plans to provide any additional convenience API built-in here. Thanks for your question/feedback! Feel free to add more comments or discussion here.
